### ISSUE TITLE
[Outlook] Dialog for Outlook web addin not rendering fonts in Outlook windows client

### ISSUE THREAD

**Issue by mihirsn** [OfficeDev/office-js#1330]
We are developing Outlook Web Addin. With the help of `Office.context.ui.displayDialogAsync` we are opening dialog box where our HTML is getting rendered. This HTML is rendering perfectly for all clients such as browsers and Outlook for Mac but problem is with Outlook windows client.
Issue is with font icons which are not getting rendered. We have pre-downloaded font icons from [icomoon](https://icomoon.io/app/#/select). We have provided HTML buttons in dialog box where user can perform some actions. And we are putting icons on these buttons for conveying button functionality.

CSS we are using:
```css
@font-face {
  font-family: 'icomoon';
  src:  url('fonts/icomoon.eot?hkrva0');
  src:  url('fonts/icomoon.eot?hkrva0#iefix') format('embedded-opentype'),
    url('fonts/icomoon.ttf?hkrva0') format('truetype'),
    url('fonts/icomoon.woff?hkrva0') format('woff'),
    url('fonts/icomoon.svg?hkrva0#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```

## Expected Behavior
Font icons should get rendered in dialog box.

## Current Behavior
In Outlook windows client font icons unable to render

## Context

Because of this issue we are not able give uniform user interface for all clients.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop__
* Host [Excel, Word, PowerPoint, etc.]: __Outlook__
* Office version number: __Microsoft Outlook for Office 365 MSO (16.0.12527.20260) 64-bit__
* Operating System: __Window 10__

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

IE Screenshot (Working as expected)

![IE](https://user-images.githubusercontent.com/42827526/90247888-2904fa80-de55-11ea-9a9a-b558eff8e5b6.JPG)
---
Outlook windows desktop client Screenshot (Font icons not rendered)

![outlook-windows-desktop-client](https://user-images.githubusercontent.com/42827526/90247890-2a362780-de55-11ea-80dd-5702bcf35ef0.JPG)

@SanketDG
