### ISSUE TITLE
Loading ‘areas’ of selected RangeAreas causes Excel to hang if the entire worksheet is selected

### ISSUE THREAD

**Issue by Rinzwind** [OfficeDev/office-js#5758]
Loading the ‘areas’ of the workbook’s selected RangeAreas causes Excel to hang if the entire active worksheet is selected, as demonstrated by the following (complete Script Lab snippet given below):

```typescript
(async () => {
  await Excel.run(async (context) => {
    context.workbook.worksheets.getActiveWorksheet().getRange().select();
    await context.sync();
    const selectedRanges = context.workbook.getSelectedRanges();
    selectedRanges.load('areas');
    await context.sync();
  });
})();
```

I tested this using Excel version 16.97.2 (25052611) on macOS 14.7.4 and Excel version 2504 (18730.20186) on Windows, it caused Excel to hang on both platforms.

**Script Lab snippet:**

```yaml
name: Test Loading ‘areas’ of Selected RangeAreas
description: ''
host: EXCEL
api_set: {}
script:
  content: |-
    (async () => {
      await Excel.run(async (context) => {
        context.workbook.worksheets.getActiveWorksheet().getRange().select();
        await context.sync();
        const selectedRanges = context.workbook.getSelectedRanges();
        selectedRanges.load('areas');
        await context.sync();
      });
    })();
  language: typescript
template:
  content: ''
  language: html
style:
  content: ''
  language: css
libraries: |-
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  https://appsforoffice.microsoft.com/lib/1/hosted/office.d.ts
```
