### ISSUE TITLE
Outlook add-in for ie browser and windows client: The ui display is strange, when block untrusted fonts in enterprise

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#989]
when block untrusted fonts in enterprise like this link: https://docs.microsoft.com/en-us/windows/security/threat-protection/block-untrusted-fonts-in-enterprise

the office 365 ui display is strange, some icon missed.

![image](https://user-images.githubusercontent.com/1878089/74628595-07ba9e80-5191-11ea-8c93-353d34f53b08.png)

and we use office css class in our add-in(which is .ms-ChoiceField-input): and **Office365Icons** font is untrusted. and this make our checkbox can't display checked status. even we have installed Office365Icons.ttf
```css
.ms-ChoiceField-input[type=checkbox]:checked+.ms-ChoiceField-field:before {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: inline-block;
    font-family: Office365Icons;
    font-style: normal;
    font-weight: 400;
    line-height: 1;
    speak: none;
    content: '\e041';
    background-color: transparent;
    border-radius: 0;
    font-size: 13px;
    top: 3px;
    left: 3px
}
```
![image](https://user-images.githubusercontent.com/1878089/74629493-50735700-5193-11ea-8cd7-38f7a1644c7a.png)

even we have installed Office365Icons.ttf
![image](https://user-images.githubusercontent.com/1878089/74629572-831d4f80-5193-11ea-98e2-7960f035417c.png)
